# Generated by Django 4.2.4 on 2023-09-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sauceuser',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
