# Generated by Django 4.2.4 on 2023-09-07 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_sauceuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sauceuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sauceuser',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='sauceuser',
            name='other_objects',
        ),
        migrations.RemoveField(
            model_name='sauceuser',
            name='specialization',
        ),
        migrations.AddField(
            model_name='employer',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адресс основного объекта'),
        ),
        migrations.AddField(
            model_name='employer',
            name='other_objects',
            field=models.TextField(blank=True, null=True, verbose_name='Прочие объекты компании'),
        ),
        migrations.AlterField(
            model_name='sauceuser',
            name='city',
            field=models.CharField(blank=True, default='Город не указан', max_length=200, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='sauceuser',
            name='profile_description',
            field=models.TextField(blank=True, default='...', null=True, verbose_name='Описание профиля'),
        ),
        migrations.AlterField(
            model_name='sauceuser',
            name='second_name',
            field=models.CharField(blank=True, default='Фамилия не указана', max_length=200, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='sauceuser',
            name='username',
            field=models.CharField(blank=True, default='Имя не указано', max_length=200, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('sauceuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('experience', models.IntegerField(blank=True, default='Опыт не указан', null=True, verbose_name='Стаж работы')),
                ('specialization', models.CharField(blank=True, max_length=150, null=True, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('main_app.sauceuser',),
        ),
    ]
