# Generated by Django 4.2.4 on 2023-09-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_sauceuser_address_remove_sauceuser_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='specialization',
            field=models.CharField(blank=True, default='Специальность не указана', max_length=150, null=True, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='other_objects',
            field=models.TextField(blank=True, default='Прочие объекты не указаны', null=True, verbose_name='Прочие объекты компании'),
        ),
    ]
