# Generated by Django 4.2.4 on 2023-09-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_candidate_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sauceuser',
            name='phone_number',
            field=models.BigIntegerField(blank=True, default='Номер телефона не указан', null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
