# Generated by Django 4.2.4 on 2023-09-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_sauceuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Стаж работы'),
        ),
        migrations.AlterField(
            model_name='sauceuser',
            name='phone_number',
            field=models.BigIntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
