# Generated by Django 4.2.4 on 2023-09-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_vacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='views_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
